"""
Create a program that will play the “cows and bulls” game with the user. The game works
like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every
digit that the user guessed correctly in the correct place, they have a “cow”. For every
digit the user guessed correctly in the wrong place is a “bull.” Every time the user
makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the
correct number, the game is over. Keep track of the number of guesses the user makes
throughout the game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""

import random

guesses = 0
game_on = True

def is_valid(guess):
    return guess.isdigit() and len(guess) == 4

def cows_and_bulls(random_number, guess):
    cows = 0
    bulls = 0
    index = 0
    for digit in str(guess):
        if guess[index] == str(random_number)[index]:
            cows += 1
        elif guess[index] in str(random_number):
            bulls += 1
        index += 1
    return cows, bulls

random_number = random.randint(1000, 9999)
print(random_number)

print('''A random 4 digit number has been generated!
Your job is to find out what what number is that!
''')

while game_on:
    user_guess = input("Please, type in your guess: ")
    while not is_valid(user_guess):
        print(f"{user_guess} is not a valid guess.")
        user_guess = input("Please, type in a valid 4 digits number: ")

    cows, bulls = cows_and_bulls(random_number, user_guess)
    print(f"{cows} cows, {bulls} bulls.")
    if cows == 4:
        game_on = False
        print(f"Congratulations! {user_guess} is the correct number!")
